import '../styles/globals.css'
import type { Metadata } from 'next'
import Nav from '@/components/Nav'
import Providers from '../(app)/providers'
{/* <Nav /> */}

export const metadata: Metadata = {
  title: 'ft_trancendence',
  description: 'Generated by 42 students',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
		<body >
      <div className=' bg-cover bg-gradient-to-bl from-blue-100 to-white'>
      <Providers >
			  {children}
      </Providers>
      </div>
		</body>
    </html>
  )
}
